debug:
  error: false

pagespy:
  enabled: false

download:
  defaultHighest: false
  filenameTemplate: "{{filename}}_{{spec}}"
  dir: "%UserDownloads%"
  pauseWhenDownload: false
  playDoneAudio: true
  frontend: false

api:
  protocol: "http"
  hostname: "127.0.0.1"
  port: 2022

proxy:
  system: true
  hostname: "127.0.0.1"
  port: 2023

channels:
  disableLocationToHome: false

mp:
  remoteServer:
    protocol: "http"
    hostname: "127.0.0.1"
    port: 2022
  refreshToken: ""
  tokenFilepath: ""
  refreshSkipMinutes: 20
  maxWebsocketClients: 5
