debug:
  error: false

pagespy:
  enabled: false

download:
  defaultHighest: false
  filenameTemplate: "{{filename}}_{{spec}}"
  dir: "%UserDownloads%"
  pauseWhenDownload: false
  playDoneAudio: true
  frontend: false
  forceCheckAllFeeds: false
  remoteServer:
    enabled: false
    protocol: "http"
    hostname: "192.168.1.2"
    port: 2022

api:
  protocol: "http"
  hostname: "127.0.0.1"
  port: 2022

proxy:
  system: true
  hostname: "127.0.0.1"
  port: 2023

channels:
  disableLocationToHome: false

mp:
  disabled: true
  remoteServer:
    protocol: "http"
    hostname: ""
    port: 80
  refreshToken: "wx_channels_download"
  tokenFilepath: ""
  refreshSkipMinutes: 20
  maxWebsocketClients: 5

cloudflare:
  accountId: ""
  apiToken: ""
  refreshToken: "wx_channels_download"
  adminToken: ""
  workerName: "mp-rss-api"
  d1Name: "mp-rss-db"
